User profile
Cook-sy/cooksy pull request #151
Opened 2017-06-13 18:55 UTC by vicalden23

closes #46 
closes #48

2017-06-13 21:58 UTC, obay-mardini requested changes
looks good to me except for some styling issues

2017-06-13 21:58 UTC, obay-mardini commented on client/src/actions/purchaseActions.js
> +  const userId = user && user.sub;
do we need user and userId variables in here?

2017-06-13 21:58 UTC, obay-mardini commented on client/src/containers/Homepage.js
> +
i don't think this break line is important

2017-06-13 21:58 UTC, obay-mardini commented on client/src/containers/UserProfile.js
> +  }
can you take out the breaklines in lines 17 and 19

2017-06-13 22:17 UTC, vicalden23 commented
👍

2017-06-13 22:26 UTC, obay-mardini approved these changes

2017-06-13 22:51 UTC, obay-mardini requested changes

2017-06-13 22:51 UTC, obay-mardini commented on client/src/reducers/purchaseReducer.js
> +import { GET_PURCHASES } from '../actions/purchaseActions';
can you import GET_PURCHASES from '../actions' instead

2017-06-14 01:12 UTC, obay-mardini approved these changes

2017-06-14 01:45 UTC, obay-mardini commented
LGTM

2017-06-14 02:02 UTC, merged