Feat/create request card
Cook-sy/cooksy pull request #153
Opened 2017-06-13 22:34 UTC by obay-mardini

2017-06-13 22:36 UTC, obay-mardini commented on client/src/containers/RequestCard.js
> +            props.orderRequestedMeal({ num: 1, requestId: props.requestId })}
I hard coded the nun on purpose just to showcase how the arguments for the orderRequestMeal is going to look like

2017-06-14 02:02 UTC, gzeegz requested changes

2017-06-14 02:02 UTC, gzeegz commented on client/src/actions/requestActions.js
> +	};
Let's fix the indentation in this file.

2017-06-14 18:00 UTC, gzeegz commented
See PR #158

2017-06-14 18:00 UTC, closed without merging